{{/*
  Common labels and selectors. Each component has its own selector but
  shares the chart-managed `app.kubernetes.io/part-of` so cluster tooling
  (Service mesh, dashboards) can scope a query to "everything stowage".
*/}}
{{- define "stowage.commonLabels" -}}
app.kubernetes.io/part-of: stowage
app.kubernetes.io/managed-by: {{ .Release.Service | default "Helm" }}
helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" }}
{{- end -}}

{{- define "stowage.dashboardLabels" -}}
{{ include "stowage.commonLabels" . }}
app.kubernetes.io/name: stowage
app.kubernetes.io/component: dashboard
{{- end -}}

{{- define "stowage.dashboardSelector" -}}
app.kubernetes.io/name: stowage
app.kubernetes.io/component: dashboard
{{- end -}}

{{- define "stowage.operatorLabels" -}}
{{ include "stowage.commonLabels" . }}
app.kubernetes.io/name: stowage-operator
app.kubernetes.io/component: operator
{{- end -}}

{{- define "stowage.operatorSelector" -}}
app.kubernetes.io/name: stowage-operator
app.kubernetes.io/component: operator
{{- end -}}

{{/*
  In-cluster URL the operator stamps into every consumer Secret as
  AWS_ENDPOINT_URL. Points at the stowage Service on the embedded proxy
  port (s3_proxy.listen :8090).
*/}}
{{- define "stowage.proxyEndpointURL" -}}
http://stowage.{{ .Values.namespace }}.svc.cluster.local:8090
{{- end -}}

{{/*
  imagePullSecrets renders the Pod-spec field. Names existing Secrets in
  .Values.namespace; the chart does not create dockerconfigjson Secrets.
  Emits nothing when the list is empty.
*/}}
{{- define "stowage.imagePullSecrets" -}}
{{- with .Values.image.pullSecrets -}}
imagePullSecrets:
{{- range . }}
  - name: {{ . }}
{{- end }}
{{- end -}}
{{- end -}}

{{/*
  secretKey resolves the AES-256 root key used to seal at-rest secrets.
  Resolution order:
   1. Explicit .Values.secretKey
   2. Existing chart-managed Secret in the cluster (helm upgrade reuses it)
   3. Freshly generated key (sha256 of 64 random alphanum chars; 64 hex
      chars, which secrets.New parses as 32 bytes)
*/}}
{{- define "stowage.secretKey" -}}
{{- if .Values.secretKey -}}
{{ .Values.secretKey }}
{{- else -}}
{{- if not (hasKey .Values "_secretKeyCache") -}}
  {{- $existing := lookup "v1" "Secret" .Values.namespace "stowage-secret-key" -}}
  {{- $key := "" -}}
  {{- if and $existing (hasKey (default (dict) $existing.data) "STOWAGE_SECRET_KEY") -}}
    {{- $key = (index $existing.data "STOWAGE_SECRET_KEY" | b64dec) -}}
  {{- else -}}
    {{- $key = randAlphaNum 64 | sha256sum -}}
  {{- end -}}
  {{- $_ := set .Values "_secretKeyCache" $key -}}
{{- end -}}
{{ .Values._secretKeyCache }}
{{- end -}}
{{- end -}}

{{/*
  webhookCert returns a dict with keys caCrt, tlsCrt, tlsKey (all base64-
  encoded PEM) for the chart-managed self-signed mode. The result is
  memoized on .Values._webhookCertCache so repeat calls across template
  files see the same cert. Resolution order:
   1. Cached dict on .Values._webhookCertCache
   2. Existing Secret (so `helm upgrade` doesn't rotate the cert)
   3. Freshly generated CA + server cert
*/}}
{{- define "stowage.webhookCert" -}}
{{- if not (hasKey .Values "_webhookCertCache") -}}
  {{- $cache := dict -}}
  {{- $svc := printf "stowage-operator-webhook.%s.svc" .Values.namespace -}}
  {{- $altNames := list
      (printf "stowage-operator-webhook.%s" .Values.namespace)
      $svc
      (printf "%s.cluster.local" $svc) -}}
  {{- $existing := lookup "v1" "Secret" .Values.namespace "stowage-operator-webhook-cert" -}}
  {{- if and $existing (hasKey (default (dict) $existing.data) "tls.crt") (hasKey (default (dict) $existing.data) "ca.crt") -}}
    {{- $cache = dict
        "caCrt"  (index $existing.data "ca.crt")
        "tlsCrt" (index $existing.data "tls.crt")
        "tlsKey" (index $existing.data "tls.key") -}}
  {{- else -}}
    {{- $days := int .Values.webhook.selfSigned.validityDays -}}
    {{- $ca := genCA "stowage-operator-webhook-ca" $days -}}
    {{- $cert := genSignedCert $svc nil $altNames $days $ca -}}
    {{- $cache = dict
        "caCrt"  ($ca.Cert | b64enc)
        "tlsCrt" ($cert.Cert | b64enc)
        "tlsKey" ($cert.Key  | b64enc) -}}
  {{- end -}}
  {{- $_ := set .Values "_webhookCertCache" $cache -}}
{{- end -}}
{{- .Values._webhookCertCache | toJson -}}
{{- end -}}

{{/*
  webhookCABundle resolves the CA bundle stamped into the
  ValidatingWebhookConfiguration. Precedence:
   1. selfSigned.enabled — bundle generated by webhookCert
   2. explicit webhook.caBundle
   3. "" (cert-manager annotation path will inject it)
*/}}
{{- define "stowage.webhookCABundle" -}}
{{- if .Values.webhook.selfSigned.enabled -}}
{{- $cert := fromJson (include "stowage.webhookCert" .) -}}
{{ $cert.caCrt }}
{{- else -}}
{{ .Values.webhook.caBundle }}
{{- end -}}
{{- end -}}
