// Copyright (C) 2026 Damian van der Merwe
// SPDX-License-Identifier: AGPL-3.0-or-later

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code hand-written to mirror what controller-gen would produce.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *AdminCredentialsRef) DeepCopyInto(out *AdminCredentialsRef) {
	*out = *in
}

func (in *AdminCredentialsRef) DeepCopy() *AdminCredentialsRef {
	if in == nil {
		return nil
	}
	out := new(AdminCredentialsRef)
	in.DeepCopyInto(out)
	return out
}

func (in *CABundleRef) DeepCopyInto(out *CABundleRef) {
	*out = *in
}

func (in *CABundleRef) DeepCopy() *CABundleRef {
	if in == nil {
		return nil
	}
	out := new(CABundleRef)
	in.DeepCopyInto(out)
	return out
}

func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
	if in.CABundleSecretRef != nil {
		out.CABundleSecretRef = new(CABundleRef)
		*out.CABundleSecretRef = *in.CABundleSecretRef
	}
}

func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *S3BackendSpec) DeepCopyInto(out *S3BackendSpec) {
	*out = *in
	out.AdminCredentialsSecretRef = in.AdminCredentialsSecretRef
	if in.TLS != nil {
		out.TLS = new(TLSSpec)
		in.TLS.DeepCopyInto(out.TLS)
	}
}

func (in *S3BackendSpec) DeepCopy() *S3BackendSpec {
	if in == nil {
		return nil
	}
	out := new(S3BackendSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *S3BackendStatus) DeepCopyInto(out *S3BackendStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *S3BackendStatus) DeepCopy() *S3BackendStatus {
	if in == nil {
		return nil
	}
	out := new(S3BackendStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *S3Backend) DeepCopyInto(out *S3Backend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *S3Backend) DeepCopy() *S3Backend {
	if in == nil {
		return nil
	}
	out := new(S3Backend)
	in.DeepCopyInto(out)
	return out
}

func (in *S3Backend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *S3BackendList) DeepCopyInto(out *S3BackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]S3Backend, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *S3BackendList) DeepCopy() *S3BackendList {
	if in == nil {
		return nil
	}
	out := new(S3BackendList)
	in.DeepCopyInto(out)
	return out
}

func (in *S3BackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BackendRef) DeepCopyInto(out *BackendRef) {
	*out = *in
}

func (in *BackendRef) DeepCopy() *BackendRef {
	if in == nil {
		return nil
	}
	out := new(BackendRef)
	in.DeepCopyInto(out)
	return out
}

func (in *ConnectionSecretRef) DeepCopyInto(out *ConnectionSecretRef) {
	*out = *in
}

func (in *ConnectionSecretRef) DeepCopy() *ConnectionSecretRef {
	if in == nil {
		return nil
	}
	out := new(ConnectionSecretRef)
	in.DeepCopyInto(out)
	return out
}

func (in *RotationPolicy) DeepCopyInto(out *RotationPolicy) {
	*out = *in
}

func (in *RotationPolicy) DeepCopy() *RotationPolicy {
	if in == nil {
		return nil
	}
	out := new(RotationPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *AnonymousAccess) DeepCopyInto(out *AnonymousAccess) {
	*out = *in
}

func (in *AnonymousAccess) DeepCopy() *AnonymousAccess {
	if in == nil {
		return nil
	}
	out := new(AnonymousAccess)
	in.DeepCopyInto(out)
	return out
}

func (in *BucketQuota) DeepCopyInto(out *BucketQuota) {
	*out = *in
	if in.Soft != nil {
		soft := in.Soft.DeepCopy()
		out.Soft = &soft
	}
	if in.Hard != nil {
		hard := in.Hard.DeepCopy()
		out.Hard = &hard
	}
}

func (in *BucketQuota) DeepCopy() *BucketQuota {
	if in == nil {
		return nil
	}
	out := new(BucketQuota)
	in.DeepCopyInto(out)
	return out
}

func (in *BucketClaimSpec) DeepCopyInto(out *BucketClaimSpec) {
	*out = *in
	out.BackendRef = in.BackendRef
	if in.WriteConnectionSecretToRef != nil {
		out.WriteConnectionSecretToRef = new(ConnectionSecretRef)
		*out.WriteConnectionSecretToRef = *in.WriteConnectionSecretToRef
	}
	if in.RotationPolicy != nil {
		out.RotationPolicy = new(RotationPolicy)
		*out.RotationPolicy = *in.RotationPolicy
	}
	if in.AnonymousAccess != nil {
		out.AnonymousAccess = new(AnonymousAccess)
		*out.AnonymousAccess = *in.AnonymousAccess
	}
	if in.Quota != nil {
		out.Quota = new(BucketQuota)
		in.Quota.DeepCopyInto(out.Quota)
	}
}

func (in *BucketClaimSpec) DeepCopy() *BucketClaimSpec {
	if in == nil {
		return nil
	}
	out := new(BucketClaimSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BucketClaimStatus) DeepCopyInto(out *BucketClaimStatus) {
	*out = *in
	if in.RotatedAt != nil {
		out.RotatedAt = in.RotatedAt.DeepCopy()
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *BucketClaimStatus) DeepCopy() *BucketClaimStatus {
	if in == nil {
		return nil
	}
	out := new(BucketClaimStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *BucketClaim) DeepCopyInto(out *BucketClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *BucketClaim) DeepCopy() *BucketClaim {
	if in == nil {
		return nil
	}
	out := new(BucketClaim)
	in.DeepCopyInto(out)
	return out
}

func (in *BucketClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BucketClaimList) DeepCopyInto(out *BucketClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]BucketClaim, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *BucketClaimList) DeepCopy() *BucketClaimList {
	if in == nil {
		return nil
	}
	out := new(BucketClaimList)
	in.DeepCopyInto(out)
	return out
}

func (in *BucketClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
